Update Explainer to add new 6.4 (Consent to Track Notwithstanding a Universal GPC Signal)
w3c/gpc pull request #88
Opened 2024-12-04 04:25 UTC by j-br0

Added new section 6.4 to address #80 on when separate consent to track can override GPC.

2024-12-04 14:38 UTC, bvandersloot-mozilla approved these changes
Am improvement, particularly with the paragraph about bombarding users with consent prompts

2024-12-04 17:50 UTC, jyasskin approved these changes
I think it would still be useful to also say something very short in the normative spec itself, but this is good text for the explainer.

2024-12-04 19:21 UTC, j-br0 commented
> I think it would still be useful to also say something very short in the normative spec itself, but this is good text for the explainer.

Any recommendation on where that should be? Maybe a sentence or two in 5.3 (maybe in lieu of some of the existing language in the second half of that section which is largely duplicative of what's now in the explainer)?

2024-12-04 22:01 UTC, jyasskin commented
It ought to be somewhere in the definition of the meaning of the `Sec-GPC` header. That's in [3.3](https://www.w3.org/TR/gpc/#the-sec-gpc-header-field-for-http-requests):
> The Sec-GPC header field is a mechanism for expressing the person's [preference](https://www.w3.org/TR/gpc/#dfn-preference) for a [do-not-sell-or-share interaction](https://www.w3.org/TR/gpc/#dfn-do-not-sell-or-share-interaction) in an HTTP request (for any request method).

which refers to [section 2](https://www.w3.org/TR/gpc/#definitions):
> A do-not-sell-or-share interaction is an interaction with a website in which the person is requesting that their data not be sold to or shared with any party other than the one the person intends to interact with, or to have their data used for cross-site ad targeting, except as permitted by law.

A possible change could be "... except as permitted by law or specifically arranged between the person and the website."?

2024-12-05 17:43 UTC, rinchen commented
These changes look good to me. I don't have any opinions on Jeffrey's comment but the suggested wording looks good to me.

2024-12-09 02:38 UTC, martinthomson approved these changes
grammar is hard.  "company requests" seemed a bit off to me.

2024-12-09 02:38 UTC, martinthomson commented on explainer.md
> +When and how a separate agreement to disregard GPC requests overrides the legal status of the signal will be a matter of local law. Some jurisdictions that have explicitly endorsed GPC as a legally b
```suggestion
When and how a separate agreement to disregard GPC requests overrides the legal status of the signal will be a matter of local law. Some jurisdictions that have explicitly endorsed GPC as a legally binding opt-out signal have also placed limitations on how companies can request permission to track despite the general signal. One rationale for such limitations is that without some restrictions, users with GPC enabled could be inundated with countless requests for exceptions to track as they browse the internet — undermining the fundamental purpose of offering a simple, binary universal opt-out tool. Both California and Colorado, for example, constrain how overrides for universal opt-out signals like GPC can be requested, including rules against retaliating against users for exercising privacy rights, conditions for valid consent, and limiting how frequently companies can ask consumers to reconsider opt-out requests.
```

2025-01-16 17:45 UTC, jyasskin commented on explainer.md
> +### 6.4 Consent to Track Notwithstanding a Universal GPC Signal
Or:

```suggestion
### 6.4 Locally Overriding a Universal GPC Signal
```

2025-01-16 17:53 UTC, michaelkleber commented on explainer.md
> +A do-not-sell-or-share preference is when a person generally requests of all website publishers that their data "not be sold or shared.” However, it is possible that a particular publisher would seek
Similar to the suggested changes to the section title, maybe "so any user consent to tracking" here could be rephrased to "any consent to override" or the like.

2025-01-16 22:18 UTC, jyasskin requested changes
I'm still uncomfortable that the definition of Sec-GPC doesn't include the possibility that the user wanted it to apply generally but not on a specific website. The change in this PR, in the "User Interface Language" section, is fine to warn UAs that they shouldn't imply that it applies globally, but we ought to also accuratly define the signal itself.

2025-01-16 22:18 UTC, jyasskin commented on index.html
> +          opt-out. Many states say that a user agent may not send a universal opt-out signal by "default,"
"States" is probably ambiguous in a global context. Use either "US states" or "jurisdictions"?

2025-01-16 22:18 UTC, jyasskin commented on index.html
> +          or otherwise.
Wording nit, since "or otherwise" doesn't add any information:
```suggestion
          a universally applicable opt-out signal,
          for example because they have consent from the user to do so.
```

2025-01-16 22:18 UTC, jyasskin commented on index.html
> +          Different jurisdiction may also have different rules for when companies can override or disregard
Is the "may" needed here? Are we unsure whether the rules actually vary?

```suggestion
          Different jurisdictions also have different rules for when companies can override or disregard
```

2025-01-23 23:40 UTC, j-br0 commented on explainer.md
> +A do-not-sell-or-share preference is when a person generally requests of all website publishers that their data "not be sold or shared.” However, it is possible that a particular publisher would seek
This is a broader point about consistent terminology around tracking/selling/sharing/targeting that I will raise as a separate issue.

2025-01-23 23:41 UTC, j-br0 commented on index.html
> +          opt-out. Many states say that a user agent may not send a universal opt-out signal by "default,"
fixed

2025-01-23 23:44 UTC, j-br0 commented on index.html
> +          or otherwise.
I think there are other scenarios besides consent where a jurisdiction might say you can disregard a generally applicable signal. For example, the law may say it doesn't apply to certain controllers (e.g., small businesses below a certain threshold, nonprofits, &c).

2025-01-23 23:45 UTC, j-br0 commented on index.html
> +          Different jurisdiction may also have different rules for when companies can override or disregard
The language may differ slightly (though some statutes are identical), but in practice regulators may enforce the same way --- most statutes include language directing regulators to try to accord interpretation to be consistent with other states. I don't feel strongly though . . .

2025-01-24 00:51 UTC, jyasskin approved these changes
This looks good enough for my concern.

2025-01-24 00:51 UTC, jyasskin commented on index.html
> +          Considerations guide</a>).
Some markup nits, but also a fix to the URL: This should be

```suggestion
          a website to ignore a generally applicable [=preference=] (see
          [[[#user-interface-language]]] below and the [[[?GPC-LEGAL-CONSIDERATIONS]]]).
```

and then there should be a `localBiblio` entry above of the form:

```javascript
{
'...': '...',
          'GPC-LEGAL-CONSIDERATIONS': {
            title: 'GPC Legal and Implementation Considerations guide',
            href: 'https://github.com/w3c/gpc/blob/main/explainer.md',
          },
'...': '...'
}
```

The replacement of "§ 5.3" ensures the section number stays in sync if sections are added or removed, and the switch to a [bibliography reference](https://respec.org/docs/#reference-shorthands) instead of a plain link ensures it shows up in the informative references section at the bottom of the document. There's a second mention of this guide in section 5.3: up to you if you also replace that with the [[[?biblio reference]]].

2025-01-24 00:51 UTC, jyasskin commented on index.html
> +          or otherwise.
I think the "for example" would tell readers that there might be other scenarios. It's better than "either" because "either" implies that there are exactly two situations, and that the second one will be described, which it's not here.

2025-04-02 19:02 UTC, merged